version: 0.1
phases:
  install:
    commands:
      - npm install
      - npm install -g serverless
      - pip install --upgrade pip
      - pip install boto3
      - pip install awscli
      - npm install serverless-python-requirements --save-dev

  build:
    commands:
      - serverless create_domain
      - serverless deploy --stage dev --verbose
